language: python
python:
- 3.7
install:
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: FFJFeg3a24J4M4W4UrVVX6Vf/49qYhzug1tVVvKBfmyGsaF2gavZmO4XlwnNCWF2epi7rrnHgOP0u1na0Fa/ADDZNuAqg/d2JOoNZDfZ3G5/vYCrlE4uQS2h8uNSlhJdZEkVARL12tEoFOR4ONda92lw4lYeBJlGk+NXhGjhmusi3BueQ3gLdh3VyolOLePxYYMIROGKrRsWfoggv4UzT0LajvoKwAyg4FKO97QYy8VJQEg/4MNa3q6ToA/4rDPJP8BcnXNXWAIizMGur036xdFgp3hVbTDf2OhbLCJgJ8UVrEFUon/JIyqP5S6pVFEtM4Z8ZUPX78SJG3hOlVnKtO1i5+N47K7J3rGs1kdKIptuD1Oegug5hn4O13HrLqy1ekIL+0Qycip4ZaUeaVbt6Oht9qoy39w48c5X0yjWx3rkXcs5Sp1u1ghvRshXbmNFLu2JNNojy2DOTSwJnzEi3XcAp/Oue9BuOPgEoRRixTia/tiyN5JYbV6d0WuDNOkR67x9BMcQ3nqKKbtnN6qjzjWAfoaFDFgcELiShCTZCxQfy4w7mqehXNu/hVZy2TGE9mzoFa4cbhN+gUAn0eYqZ8mI1HVKXQHhjyHbb5FypS9L4XvQoJh0eo4IeiTfNkwtbDNKZK0DA7vQWEvZY+ZGJLEGwvqpQ23Se1SWGqIIt84=
  on:
    branch: master
    repo: ihmeuw-msca/stagemodel
    tags: true